export type ImagePlaceholder = {
  id: string;
  description: string;
  imageUrl: string;
  imageHint: string;
};

export const PlaceHolderImages: ImagePlaceholder[] = [
  {
    id: "hero-portrait",
    description: "Stylish portrait of a designer",
    imageUrl: "/logos/hafiz.jpg",
    imageHint: "male portrait",
  },
  {
    id: "logo-1",
    description: "YOUNG STARS",
    imageUrl: "/logos/7.jpg",
    imageHint: "abstract logo",
  },
  {
    id: "logo-2",
    description: "Bakers Kitchen",
    imageUrl: "/logos/8.jpg",
    imageHint: "bakery logo",
  },
  {
    id: "logo-3",
    description: "TOPFOXX",
    imageUrl: "/logos/2.jpg",
    imageHint: "logistics logo",
  },
  {
    id: "logo-4",
    description: "BADAR UL HARMANI",
    imageUrl: "/logos/15.jpg",
    imageHint: "luxury logo",
  },
  {
    id: "logo-5",
    description: "AZ GRAPIX",
    imageUrl: "/logos/12.jpg",
    imageHint: "creative logo",
  },
  {
    id: "logo-6",
    description: "Clanks",
    imageUrl: "/logos/3.jpg",
    imageHint: "abstract logo",
  },
  {
    id: "logo-7",
    description: "MBA",
    imageUrl: "/logos/4.jpg",
    imageHint: "minimalist logo",
  },
  {
    id: "logo-8",
    description: "TOYS 'N' DECOR",
    imageUrl: "/logos/5.jpg",
    imageHint: "tech logo",
  },
  {
    id: "logo-9",
    description: "NEXIT",
    imageUrl: "/logos/6.jpg",
    imageHint: "bold logo",
  },
  {
    id: "logo-10",
    description: "FIRM FOUNDATION ACADEMY",
    imageUrl: "/logos/9.jpg",
    imageHint: "modern logo",
  },
  {
    id: "logo-11",
    description: "ZAIBTRENDS",
    imageUrl: "/logos/10.jpg",
    imageHint: "elegant logo",
  },
  {
    id: "logo-12",
    description: "New Logo",
    imageUrl: "/logos/11.jpg",
    imageHint: "geometric logo",
  },
  {
    id: "logo-13",
    description: "Eboo",
    imageUrl: "/logos/13.jpg",
    imageHint: "classic logo",
  },
  {
    id: "logo-14",
    description: "BASHIR",
    imageUrl: "/logos/14.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-15",
    description: "AL KASIB DESIGNER",
    imageUrl: "/logos/AL_KASIB_DESIGNER.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-16",
    description: "AL KASIB ESTATE",
    imageUrl: "/logos/AL_KASIB_ESTATE.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-17",
    description: "AM STUDIOS",
    imageUrl: "/logos/AM_STUDIOS.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-18",
    description: "AMINE PERFEUME",
    imageUrl: "/logos/AMINE_PERFUME.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-19",
    description: "DK NEXA STUDIO",
    imageUrl: "/logos/DK_NEXA_STUDIO.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-20",
    description: "EDLENE PARFUM",
    imageUrl: "/logos/EDLENE_PARFUM.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-21",
    description: "GeethaDigital",
    imageUrl: "/logos/GeethaDigital.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-22",
    description: "LAMORE PURFUMES",
    imageUrl: "/logos/LAMORE_PURFUMES.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-23",
    description: "Syed Saad Photographer",
    imageUrl: "/logos/Logo_Syed_Saad_Photographer.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-24",
    description: "Pamela",
    imageUrl: "/logos/pemela-logo.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-25",
    description: "RAM GRAPHICS",
    imageUrl: "/logos/RAM_GRAPHICS.jpg",
    imageHint: "vibrant logo",
  },
  {
    id: "logo-26",
    description: "ZINARS LOGO",
    imageUrl: "/logos/ZINARS_LOGO.png",
    imageHint: "vibrant logo",
  },
  {
    id: "poster-1",
    description: "Closetlux",
    imageUrl: "/Poster/Closetlux.jpg",
    imageHint: "music poster",
  },
  {
    id: "poster-2",
    description: "BNB Rice Glow Kit",
    imageUrl: "/Poster/BNB.jpg",
    imageHint: "BNB poster",
  },
  {
    id: "poster-3",
    description: "Luxury Package poster",
    imageUrl: "/Poster/Luxury.jpg",
    imageHint: "Luxury Package poster",
  },
  {
    id: "poster-4",
    description: "Etigma poster",
    imageUrl: "/Poster/Etigma.jpg",
    imageHint: "tech poster",
  },
  {
    id: "poster-5",
    description: "SwiftStep",
    imageUrl: "/Poster/SwiftStep.jpg",
    imageHint: "sale poster",
  },
  {
    id: "poster-6",
    description: "MEEM SE MOHABBAT",
    imageUrl: "/Poster/MEEM.jpg",
    imageHint: "nature poster",
  },
  {
    id: "poster-7",
    description: "Grace Trends poster",
    imageUrl: "/Poster/Grace-trends.jpg",
    imageHint: "Luxury poster",
  },
  {
    id: "poster-8",
    description: "Zam Zam Perfumes",
    imageUrl: "/Poster/Zam-Zam.jpg",
    imageHint: "event poster",
  },
  {
    id: "poster-9",
    description: "Let's Go Fish",
    imageUrl: "/Poster/Let's_Go_Fish.jpg",
    imageHint: "event poster",
  },
  {
    id: "poster-10",
    description: "Qualidade poster",
    imageUrl: "/Poster/Qualidade.jpg",
    imageHint: "event poster",
  },
  {
    id: "poster-11",
    description: "BMW poster",
    imageUrl: "/Poster/BMW.jpg",
    imageHint: "event poster",
  },
  {
    id: "poster-12",
    description: "Mustang Ford",
    imageUrl: "/Poster/Mustang_Ford.jpg",
    imageHint: "event poster",
  },
  {
    id: "poster-13",
    description: "Votree poster",
    imageUrl: "/Poster/Votree.jpg",
    imageHint: "event poster",
  },
  {
    id: "poster-14",
    description: "Nike Vomero",
    imageUrl: "/Poster/Nike_Vomero.jpg",
    imageHint: "event poster",
  },
  {
    id: "poster-15",
    description: "Just Do It",
    imageUrl: "/Poster/Just_Do_It.jpg",
    imageHint: "event poster",
  },
  {
    id: "poster-16",
    description: "HB NewU",
    imageUrl: "/Poster/hbnewu.jpeg",
    imageHint: "event poster",
  },
  {
    id: "poster-17",
    description: "Passion Nike",
    imageUrl: "/Poster/Passion_Nike.jpg",
    imageHint: "event poster",
  },
  {
    id: "poster-18",
    description: "Winter Love",
    imageUrl: "/Poster/Winter_love.jpeg",
    imageHint: "event poster",
  },
  {
    id: "poster-19",
    description: "Zanjeerain",
    imageUrl: "/Poster/Zanjeerain.jpeg",
    imageHint: "event poster",
  },
  {
    id: "ui-1",
    description: "ZAIB-E-HOOR UI",
    imageUrl: "/UI/ZAIB.jpg",
    imageHint: "app screen",
  },
  {
    id: "ui-2",
    description: "Clanks Website UI",
    imageUrl: "/UI/Clanks.jpg",
    imageHint: "website design",
  },
  {
    id: "ui-3",
    description: "EBOO UI",
    imageUrl: "/UI/EBOO.jpg",
    imageHint: "dashboard ui",
  },
  {
    id: "ui-4",
    description: "TOPFOXX Store UI",
    imageUrl: "/UI/TOPFOXX.jpg",
    imageHint: "ecommerce ui",
  },
  {
    id: "brand-1",
    description: "Zam Zam Perfumes",
    imageUrl: "/Brands_Managed/Zam-Zam-Account.jpg",
    imageHint: "coffee branding",
  },
  {
    id: "brand-2",
    description: "Closetlux",
    imageUrl: "/Brands_Managed/Closetlux-account.jpg",
    imageHint: "fashion brand",
  },
  {
    id: "brand-3",
    description: "ZAIB-E-HOOR",
    imageUrl: "/Brands_Managed/ZAIB-E-HOOR.jpg",
    imageHint: "tech brand",
  },
  {
    id: "brand-4",
    description: "Haya Mirza",
    imageUrl: "/Brands_Managed/Haya-Mirza.jpg",
    imageHint: "food branding",
  },
  {
    id: "brand-5",
    description: "She Trends",
    imageUrl: "/Brands_Managed/She-Trends.jpg",
    imageHint: "fitness brand",
  },
  {
    id: "brand-6",
    description: "DHA Cinema",
    imageUrl: "/Brands_Managed/DHA_Cinema.PNG",
    imageHint: "fitness brand",
  },
  {
    id: "brand-7",
    description: "Mahwish",
    imageUrl: "/Brands_Managed/Mahwish.PNG",
    imageHint: "fitness brand",
  },
  {
    id: "brand-8",
    description: "Qistmarket",
    imageUrl: "/Brands_Managed/Qistmarket.PNG",
    imageHint: "fitness brand",
  },
  {
    id: "brand-9",
    description: "Revoo",
    imageUrl: "/Brands_Managed/Revoo.PNG",
    imageHint: "fitness brand",
  },
  {
    id: "about-photo",
    description: "Professional photo of Hafiz Ali Zaib",
    imageUrl: "/logos/about-hafiz.jpg",
    imageHint: "professional portrait",
  },
  {
    id: "education-background",
    description: "A person in a suit holding a graduation cap, representing education.",
    imageUrl: "/logos/education.jpg",
    imageHint: "graduation education",
  },
];

export const getImageById = (id: string): ImagePlaceholder | undefined => {
  return PlaceHolderImages.find(img => img.id === id);
};
